version: "3.0"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - .:/usr/src/app
    networks:
      - supermarket-network
    command: npm run start
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - supermarket-db-volume:/var/lib/postgresql/data
    networks:
      - supermarket-network

networks:
  supermarket-network:
    driver: bridge
volumes:
  supermarket-db-volume:
    driver: local
